config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/cv', to: 'pages#cv'
  get '/projets',to: 'pages#projets'
  get '/formations',to: 'pages#formations'
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def cv
  end

  def projets
  end

  def formations
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Abdulmelik SAK</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
  <div class="py-8 px-6 md:px-16 lg:px-24 lg:py-24">
    <%= render partial: 'shared/navbar' %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/cv.html.erb
<div style="height:67vh;">
  <div class="md:ml-32 mt-16 mr-4 relative h-full" style="padding-bottom: 70%">
    <iframe class="absolute inset-0 w-full h-full" src="CV_Abdulmelik_SAK.pdf"></iframe>
  </div>
</div>

app/views/pages/formations.html.erb
<div class="md:pl-32 mt-16 text-gray-900 space-y-5">
  <div class="max-w-md">
    <h2 class="text-2xl font-bold ">Le Wagon</h2>
    <p class="text-sm">Titre RNCP de niveau 6</p>
    <div class=" space-y-1 mt-3">
      <p class="text-lg">Concepteur / développeur d'application WEB</p>
      <p class="text-base">Développement d'application WEB avec Ruby on Rails, JavaScript, HTML, CSS et Tailwind avec aussi de L'UX design, Personna, User Story, Wireframe et User Journey</p>
    </div>
  </div>

  <div class="max-w-md">
    <h2 class="text-2xl font-bold ">Polytech Grenoble</h2>
    <p class="text-sm">1 an d'étude</p>
    <div class="space-y-1 mt-3">
      <p class="text-lg">Réseaux Informatique et Communications Multimédia</p>
      <p class="text-base">Programmations avec différents languages tels que JAVA, C, JavaScript, PHP, HTML, CSS, Assembleur</p>
    </div>
  </div>

  <div class="max-w-md">
    <h2 class="text-2xl font-bold ">IUT 1 Joseph Fourrier</h2>
      <p class="text-sm">DUT</p>
    <div class=" space-y-1 mt-3">
      <p class="text-lg">Réseaux et Télécommunications</p>
      <p class="text-base">Apprentissage polyvalent en réseaux et en programmations avec des languages Shell, Python, HTML, CSS, PHP, JavaScript, JAVA, Assembleur</p>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="md:pl-32 mt-16 text-gray-900">
  <div class="max-w-md">
    <h2 class="text-2xl font-bold ">Qui suis-je?</h2>
    <div class="mt-6 text-lg space-y-6">
      <p>Je suis actuellement à l'écoute d'opportunité, plus précisément dans la programmation web</p>
      <p>De nature très curieuse j'adore apprendre dans tous les domaines et relevé des défis en tout genre</p>
      <p>Attiré depuis toujours par les nouvelles technologies j'adore aussi voyager et passer mon temps au cinéma</p>
    </div>

    <div class="flex justify-end items-center mt-10">
      <div class="px-4">
        <a href="https://github.com/AbdulmelikSAK" target="_blank">
          <svg class="w-8 fill-current text-gray-800" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>GitHub icon</title><path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"/></svg>
        </a>
      </div>

      <div class="px-4">
        <a href="https://www.linkedin.com/in/abdulmelik-sak/" target="_blank">
          <svg  class="w-8 fill-current text-gray-800"role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>LinkedIn icon</title><path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/></svg>
        </a>
      </div>

      <div class="px-4">
        <a href="https://www.codewars.com/users/AbdulmelikSAK" target="_blank">
          <svg class="w-8 fill-current text-gray-800" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
          </svg>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/pages/projets.html.erb
<div class="md:pl-32 mt-16 text-gray-900 space-y-5">
  <div class="max-w-md">
    <h2 class="text-2xl font-bold ">Le Wagon Labs</h2>
    <div class="space-y-1 mt-3">
      <p class="text-lg">Projet en cours sous la tutelle du Wagon Lyon pour créé un lieu d'échange entre entrepreneurs et développeur sortant du Wagon Lyon</p>
      <p class="text-base">Projet en cours de développement ...</p>
    </div>
  </div>
  <div class="max-w-md">
    <h2 class="text-2xl font-bold ">Click & Stalk</h2>
    <div class="space-y-2 mt-3">
      <p class="text-lg">Site destiné aux personnes en recherche d'emploi pour leur permettre de vérifier leur réseaux sociaux, avant de postuler dans certains poste, et ainsi de ce rendre compte des défauts de leur compte linkedin ou de l'image que renvois les réseaux socieux d'eux même</p>
      <div class="relative h-2/3" style="padding-bottom: 70%">
        <iframe class="absolute inset-0 w-full h-full" src="https://www.youtube.com/embed/tkn28oVl8Fs" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<header class="flex justify-between md:justify-start md:pl-16 items-center">
  <div class="flex items-center">
    <div class="pr-4">
      <a href="/"><%= image_tag "melik.jpg", alt: "melik", class: 'w-12 rounded-full' %></a>
    </div>
    <h3 class="font-bold text-2xl text-gray-900">Abdulmelik SAK</h3>
    <div class ="hidden md:block pl-16 space-x-5">
      <%= link_to 'CV', cv_path, class: 'font-semibold text-gray-900 hover:text-gray-500' %>
      <%= link_to 'FORMATIONS', formations_path, class: 'font-semibold text-gray-900 hover:text-gray-500'  %>
      <%= link_to 'PROJETS', projets_path, class: 'font-semibold text-gray-900 hover:text-gray-500' %>
    </div>
  </div>
  <button id="menu_btn">
    <div class="md:hidden">
      <svg class="w-8" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
      </svg>
    </div>
  </button>
</header>

<div class="menu hidden md:hidden">
  <div class="mt-8 ml-8 space-y-8 flex flex-col">
      <%= link_to 'CV', cv_path, class: 'font-semibold text-gray-900' %>
      <%= link_to 'FORMATIONS', formations_path, class: 'font-semibold text-gray-900'  %>
      <%= link_to 'PROJETS', projets_path, class: 'font-semibold text-gray-900' %>
  </div>
</div>